# -*- mode: ruby -*-
# vi: set ft=ruby :

# script vagrant pour la machine virtuelle defensive.
Vagrant.configure("2") do |config|
  
    # VM box to Debian 11
    config.vm.box = "generic/debian11"
  
    # Set VM name
    config.vm.define "Offensive"

    # Set network configuration
    config.vm.network "private_network", ip: "192.168.10.11"

    # Configurations des ports tcp et udp
    config.vm.network "forwarded_port", guest: 80, host: 8080, protocol: "tcp"
    config.vm.network "forwarded_port", guest: 23, host: 2323, protocol: "tcp"
    config.vm.network "forwarded_port", guest: 53, host: 5353, protocol: "udp"

    # Désactiver GUI de la machine virtuelle, spécifier la RAM et le CPU
    config.vm.provider "virtualbox" do |vb|
        vb.name = "Offensive"
        vb.gui = false
        vb.memory = "2048"
        vb.cpus = 2
    end
  
    # Install les packets pour la machine defensive
    config.vm.provision "shell", inline: <<-SHELL
       apt-get update
       apt-get install -y build-essential 
       apt-get install -y bash 
       apt-get install -y zsh
       apt install -y gpgv2 autoconf bison postgresql libaprutil1 libgmp3-dev libpcap-dev openssl libpq-dev libreadline6-dev libsqlite3-dev libssl-dev locate libsvn1 libtool libxml2 libxml2-dev libxslt-dev wget libyaml-dev ncurses-dev postgresql-contrib xsel zlib1g zlib1g-dev
       curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall 
       chmod 755 msfinstall  
       ./msfinstall
       apt-get install -y hping3 nmap hydra-gtk
    SHELL
    
end